from easycv.image_loader import Image

img = Image()
img.from_file('../images/stranthen.jpg', image_type='rgb')
img.show()
img1 = img.translation_band(band='R', delta=10)
img1.show()
img1.save_to(f'../images/test_r+10.jpg')
img2 = img.translation_band(band='R', delta=-10)
img2.show()
img2.save_to(f'../images/test_r-10.jpg')
img3 = img.rotation_band('R', fix=127, slope=4)
img3.show()
img3.save_to(f'../images/test_rr+4.jpg')
img4 = img.rotation_band('R', fix=127, slope=-4)
img4.show()
img4.save_to(f'../images/test_rr-4.jpg')
